### ISSUE TITLE
tokenizer files in uploaded models

### ISSUE THREAD

**Issue by fajri91** [FomalhautB/KM-BART-ACL#3]
Hi, can I have tokenizer files for each model as well?
I only found `config.json` and `pytorch_model.bin` in the zip.

**Comment by fajri91** [comment]
Hi @procedure2012 @FomalhautB 

can you please also share the tokenizer files for `bart-full-model`? The config shows that the vocab size is 50320. However, after using `facebook/bart-base` (originally has 50265 tokens) and adding some special tokens defined in `src/data/tokenization.py` the size is 50281. What are the 39 missing tokens that need to be added?

**Comment by procedure2012** [comment]
The 39 missing tokens are blank tokens. They never appear in any datasets. They are transparent to the model. There are actually only 50281 tokens in the tokenizer. 

We set the vocab size as 50320 because we don't want to frequently change the model's structure. We can add other tokens to test different input formats without changing the model's structure. Those weights with the same structure can be directly used for the evaluation and downstream tasks.

**Comment by fajri91** [comment]
All right, thank you for the answer :)
I'll close this issue.
